# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Пользователь\Documents\GitHub\EpidemicSimulation\info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(842, 241)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 851, 81))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 128);\n"
"background-color:rgb(0, 0, 127);\n"
"border-radius: 5px;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 851, 111))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 128);\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius: 5px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(-10, 190, 861, 51))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 128);\n"
"background-color:rgb(0, 0, 127);\n"
"border-radius: 5px;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Правила пользования</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Сумма некоторых коэфицентов должна быть меньше 1, но больше 0, а именно:</p><p align=\"center\">0 &lt; k1 + k5 &lt;1</p><p align=\"center\">0 &lt; k2 + k6 &lt;1</p><p align=\"center\">0 &lt; k4 + k7 &lt; 1</p><p align=\"center\">0 &lt; k3 &lt; 1</p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
